id: I2F7C756C
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-08-16T14:22:36.290072'
last_modified: '2022-08-16T14:22:36.290088'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: mon
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
